/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Added: typeof import('./../components/payUI/added.vue')['default']
    CartBag: typeof import('./../components/ui/cart-bag.vue')['default']
    ChangeNumber: typeof import('./../components/mealsCom/change-number.vue')['default']
    Dialogue: typeof import('./../components/ui/dialogue.vue')['default']
    Foote: typeof import('./../layout/foote.vue')['default']
    Layout: typeof import('./../layout/layout.vue')['default']
    Meal: typeof import('./../components/mealsCom/Meal.vue')['default']
    Meals: typeof import('./../components/ui/Meals.vue')['default']
    Message: typeof import('./../components/mealsCom/message.vue')['default']
    Message2: typeof import('./../components/payUI/message2.vue')['default']
    Pay: typeof import('./../components/payUI/pay.vue')['default']
    Paymeal: typeof import('./../components/payUI/paymeal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/ui/search.vue')['default']
    TopNav: typeof import('./../layout/topNav.vue')['default']
  }
}
